rabbit:
  host: "localhost"
  port: 44430
  user: "guest"
  pass: "guest"

quote server:
  host: "localhost"
  port: 4443
  retry: 150 # milliseconds
  backoff: 10 # milliseconds

redis:
  host: "localhost"
  port: 44431
  max idle connections: 5
  max active connections: 0 # 0 = unlimited
  idle timeout: 30 # seconds
  key prefix: "quotemgr:"

# This defines the retention policy for quotes in the cache.
# Each quote is valid for 60s from the timestamp returned from the
# quoteserver. We want to stagger the times that quotes expire
# so we don't get synchronized refresh cycles.
# Each quote is good for (base - random backoff) in seconds.
quote policy:
  base ttl: 59
  backoff ttl: 4 # ranges 0 -> n
