rabbit:
  host: "localhost"
  port: 44430
  user: "guest"
  pass: "guest"

quote server:
  host: "quoteserve.seng.uvic.ca"
  port: 4443
  retry: 150
  backoff: 10

redis:
  host: "localhost"
  port: 44431
  max idle connections: 5
  max active connections: 0
  idle timeout: 30
  key prefix: "quotemgr:"

quote policy:
  base ttl: 59
  backoff ttl: 4
